on:
  push:
    tags:
      - '*'
jobs:
  build-x86_64:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        clean: false
        submodules: recursive

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -q -y
        sudo apt-get install -y make gcc g++ python3 python3-dev python3-pip \
           python3-pytest python3-numpy python3-scipy iverilog wget curl \
           default-jre libxrender-dev libxtst-dev libtinfo5 \
           libgtk2.0-0 git \
           zip unzip dfu-util fakeroot u-boot-tools device-tree-compiler mtools \
           bison flex libncurses5-dev libssl-dev bc cpio rsync cmake \
           libgtk-3-0 xz-utils libgmp-dev libmpc-dev bootgen-xlnx
      
    # - name: Checkout
    #   shell: bash
    #   run: |
    #     git clone --recursive --depth 1 https://github.com/F5OEO/plutosdr-fw
    # prog1 & prog2 && fg
    - name: Cache build
      id: cache-build
      uses: actions/cache@v4
      with:
        fail-on-cache-miss: true
        # Path of the directory to cache
        path: /home/runner/work/plutosdr-fw/plutosdr-fw/
        # Unique key for the cache
        key: Linux-cache-198acefdaf363c35deacc9cf5d1b64835f7a1af569cd8e7ea820fe642612c055
        restore-keys: |
          Linux-cache-198acefdaf363c35deacc9cf5d1b64835f7a1af569cd8e7ea820fe642612c055
          Linux-cache-
          Linux-
          
    - if: ${{ steps.cache-build.outputs.cache-hit != 'true' }}
      name: Build PlutoDatvFirmware from scratch
      continue-on-error: true
      run: |
        make 
        TARGET=plutoplus make 
        TARGET=e200 make 

    - name: Use cache folder
      run: |
        make zip-all


    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: PlutoDVB2_${{  github.ref_name }}
        title: Release ${{  github.ref_name }}
        prerelease: false
        files: |
            plutosdr-fw/Release/**.zip
