on: [push, pull_request]

jobs:
  build-x86_64:
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} x86_64
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install -y make gcc g++ python3 python3-dev python3-pip \
           python3-pytest python3-numpy python3-scipy iverilog wget curl \
           default-jre libxrender-dev libxtst-dev libtinfo5 \
           libgtk2.0-0 git \
           zip unzip dfu-util fakeroot u-boot-tools device-tree-compiler mtools \
           bison flex libncurses5-dev libssl-dev bc cpio rsync cmake \
           libgtk-3-0 xz-utils libgmp-dev libmpc-dev 

    - name: Build PlutoDatvFirmware
      shell: bash
      run: |
        make 
        
steps:
- checkout: self
  submodules: recursive
 