on: [push, pull_request]

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install -y make gcc g++ python3 python3-dev python3-pip \
           python3-pytest python3-numpy python3-scipy iverilog wget curl \
           default-jre libxrender-dev libxtst-dev libtinfo5 \
           libgtk2.0-0 git \
           zip unzip dfu-util fakeroot u-boot-tools device-tree-compiler mtools \
           bison flex libncurses5-dev libssl-dev bc cpio rsync cmake \
           libgtk-3-0 xz-utils libgmp-dev libmpc-dev

    - name: Checkout
      shell: bash
      run: |
        git clone --recursive --depth 1 https://github.com/F5OEO/plutosdr-fw
    

    - name: Build PlutoDatvFirmware
      shell: bash
      run: |
        cd plutosdr-fw && make

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: plutodvb2_${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    - name: Upload Release Asset dfu
      id: upload-release-asset-dfu 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./plutosdr-fw/build/pluto.dfu
        asset_name: pluto.dfu
        asset_content_type: application/octet-stream
    - name: Upload Release Asset frm
      id: upload-release-asset-frm 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./plutosdr-fw/build/pluto.frm
        asset_name: pluto.frm
        asset_content_type: application/octet-stream
    
