on: [push, pull_request]

jobs:
  build-x86_64:
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} x86_64
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Install dependencies
      shell: bash
      run: |
        apt-get install -y make gcc g++ python3 python3-dev python3-pip \
           python3-pytest python3-numpy python3-scipy iverilog wget curl \
           default-jre libxrender-dev libxtst-dev libtinfo5 \
           libgtk2.0-0 git \
           zip unzip dfu-util fakeroot u-boot-tools device-tree-compiler mtools \
           bison flex libncurses5-dev libssl-dev bc cpio rsync cmake \
           libgtk-3-0 xz-utils libgmp-dev libmpc-dev 

    - name: Build PlutoDatvFirmware
      shell: bash
      run: |
        make clean && make CC=gcc-9
        make clean && make CC=gcc-10

  build-arm:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: armv6
            distro: buster
          - arch: armv7
            distro: buster
          - arch: aarch64
            distro: ubuntu20.04

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: uraimo/run-on-arch-action@v2.6.0
        name: Build Matrix
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          githubToken: ${{ github.token }}

          shell: /bin/sh

          install: |
            case "${{ matrix.distro }}" in
              ubuntu)
               make 
                ;;
              ubuntu20.04)
                make 
                ;;
            esac

          run: |
            case "${{ matrix.distro }}" in
              buster)
                make clean && make CC=gcc-7
                make clean && make CC=gcc-8
                ;;
              ubuntu20.04)
                make clean && make CC=gcc-9
                make clean && make CC=gcc-10
                ;;
            esac